name: "Teste de Action"
on:
    issues:
        types: [opened]
    pull_request:
        types: [opened]

jobs:
    teste-action-job:
        permissions: 
            issues: write
            pull-requests: write
        runs-on: ubuntu-latest
        name: Execucação de Custom Action
        steps:
            - name: Adicionando Comentário
              uses: limalucas99/custom-action-docker@v1.0.0
              with:
                GH_TOKEN: ${{ secrets.GH_TOKEN }}
                issue-id: ${{ github.event.issue.number }}
                comment: "Teste de comentário composite"
                GH_REPOSITORY: ${{ github.repository }}
